### PR TITLE
Feature/query opts

### PR DESCRIPTION
**Pull request by zjr**
This adds the ability to add query options to getVersion (e.g. `{ lean: true }`).

Again, will update readme if you want to merge these.

### CODE REVIEW

**Comment by zjr** [comment]
@mimani Merge conflicts on this branch are fixed. Again, sorry about those, side effect of the weird split.

**Comment by zjr** [comment]
@mimani please let me know if you would still like to review these PRs before I merge them.

**Comment by mimani** [comment]
@zjr These looks good, you can go ahead ahead and merge these. Thanks for enriching this repo, which was quite dormant for some time :)

**Comment by zjr** [comment]
@mimani no problem! Thank you for being receptive to the changes and adding me as a collaborator. Sometime in the next day or two I'll be making some more changes and then we'll probably want to make a new release.

**Comment by mimani** [comment]
Sure, I have added you as collaborator on npm as well, so that you will be able to push on npm as well.

**Comment by zjr** [comment]
Great, thank you very much.

**Pull request merged**
