### PR TITLE
transaction support & fix upsert:true problem (modify test case to check upsert problem)

### PR DESCRIPTION
**Pull request by dhwpong**
pass mongo session to saveHistory, so that saveHistory is part of the
transaction, and when transaction get aborted history will get rollback also.

(note: transaction need mongoose version 5.2 and above)

### CODE REVIEW

**Comment by mimani** [comment]
Can you add an unit test for this as well.

**Comment by dhwpong** [comment]
> Can you add an unit test for this as well.

not sure how to, since needed mongoose 5.2 and above and your packages are 4.13.9

**Comment by dhwpong** [comment]
I have added the transaction test, but you need to set the "testTransaction" to true in the test script after made all the necessary setup, ie. the cluster DB and mongoose version > 5.2

**Comment by jarretmoses** [comment]
@dhwpong is this definitely working? Maybe I'm misunderstanding `__session: session` `__session` does not exist on the object you are restructuring from but `session does.

```
  const { __user: user, __reason: reason, session } =
        (queryObject && queryObject.options) || currentObject;
```

**Comment by dhwpong** [comment]
The original code does not look at session, It was done intentionally, if you pass in the option with __session: session, it will be part of the transaction, if you don’t it will be like the original behavior of NOT being part of the transaction.  In case people expect the behavior of having a history even it was aborted?

**Pull request merged**
